name: CI - Go Tests

on:
  push:
    branches: [ "**" ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Lint + Vet + Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
          cache: true

      - name: Download deps
        run: go mod download

      - name: Lint (golangci-lint)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          args: --timeout=3m

      - name: Vet
        run: go vet ./...

      - name: Build (verificação de compilação)
        run: go build ./...

      - name: Testes com race + cobertura
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Publicar cobertura
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out